In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.svm import SVC

In [2]:
weather = pd.read_excel(r'G:\机器学习资料\菜菜的skleran\08支持向量机下\weather.xlsx',encoding='gbk',index_col=0)
colums_dict = {'Date':'观察日期',
'Location' :'获取该信息的气象站的名称',
'MinTemp': '以摄氏度为单位的最低温度',
'MaxTemp': '以摄氏度为单位的最高温度',
'Rainfall': '当天记录的降雨量',
'Evaporation': '到早上9点之前的24小时的A级蒸发量',
'Sunshine': '白日受到日照的完整小时',
'WindGustDir': '在到午夜12点前的24小时中的最强风的风向',
'WindGustSpeed': '在到午夜12点前的24小时中的最强风速',
'WindDir9am' :'上午9点时的风向',
'WindDir3pm': '下午3点时的风向',
'WindSpeed9am' :'上午9点之前每个十分钟的风速的平均值',
'WindSpeed3pm' :'下午3点之前每个十分钟的风速的平均值',
'Humidity9am' :'上午9点的湿度',
'Humidity3pm': '下午3点的湿度',
'Pressure9am': '上午9点平均海平面上的大气压',
'Pressure3pm': '下午3点平均海平面上的大气压',
'Cloud9am': '上午9点的天空被云层遮蔽的程度',
'Cloud3pm': '下午3点的天空被云层遮蔽的程度',
'Temp9am': '上午9点的摄氏度温度',
'Temp3pm': '下午3点的摄氏度温度',
'RainTomorrow' :'目标变量',}

In [3]:
weather.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainTomorrow'],
      dtype='object')

In [4]:
weather.rename(columns=colums_dict,inplace=True)

In [5]:
x = weather.loc[:,weather.columns!= '目标变量']
y= weather.loc[:,'目标变量']

In [6]:
x.shape,y.shape

((142193, 21), (142193,))

In [7]:
x.head()

,观察日期,获取该信息的气象站的名称,以摄氏度为单位的最低温度,以摄氏度为单位的最高温度,当天记录的降雨量,到早上9点之前的24小时的A级蒸发量,白日受到日照的完整小时,在到午夜12点前的24小时中的最强风的风向,在到午夜12点前的24小时中的最强风速,上午9点时的风向,...,上午9点之前每个十分钟的风速的平均值,下午3点之前每个十分钟的风速的平均值,上午9点的湿度,下午3点的湿度,上午9点平均海平面上的大气压,下午3点平均海平面上的大气压,上午9点的天空被云层遮蔽的程度,下午3点的天空被云层遮蔽的程度,上午9点的摄氏度温度,下午3点的摄氏度温度
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,20.0,24.0,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,4.0,22.0,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,19.0,26.0,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,11.0,9.0,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,7.0,20.0,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7

In [8]:
x.isna().mean()

观察日期                     0.000000
获取该信息的气象站的名称             0.000000
以摄氏度为单位的最低温度             0.004480
以摄氏度为单位的最高温度             0.002265
当天记录的降雨量                 0.009888
到早上9点之前的24小时的A级蒸发量       0.427890
白日受到日照的完整小时              0.476929
在到午夜12点前的24小时中的最强风的风向    0.065615
在到午夜12点前的24小时中的最强风速      0.065193
上午9点时的风向                 0.070418
下午3点时的风向                 0.026570
上午9点之前每个十分钟的风速的平均值       0.009480
下午3点之前每个十分钟的风速的平均值       0.018496
上午9点的湿度                  0.012476
下午3点的湿度                  0.025388
上午9点平均海平面上的大气压           0.098556
下午3点平均海平面上的大气压           0.098324
上午9点的天空被云层遮蔽的程度          0.377353
下午3点的天空被云层遮蔽的程度          0.401525
上午9点的摄氏度温度               0.006358
下午3点的摄氏度温度               0.019171
dtype: float64

In [9]:
np.unique(y)

array(['No', 'Yes'], dtype=object)

In [10]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.3,random_state=42)#随机抽样
print(xtrain.shape,xtest.shape,ytrain.shape,ytest.shape,)
#恢复索引
for i in [xtrain, xtest, ytrain, ytest]:
    i.index = range(i.shape[0])

(99535, 21) (42658, 21) (99535,) (42658,)

In [11]:
ytrain.value_counts()

No     77183
Yes    22352
Name: 目标变量, dtype: int64

In [12]:
ytest.value_counts()

No     33133
Yes     9525
Name: 目标变量, dtype: int64

In [13]:
22352/77183,9525/33133

(0.2895974502157211, 0.28747774122476083)

In [14]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder().fit(ytrain)

In [15]:
ytrain = pd.DataFrame(encoder.transform(ytrain))
ytest = pd.DataFrame(encoder.transform(ytest))

In [16]:
xtrain.describe([0.01,0.05,0.1,0.25,0.5,0.75,0.9,0.99]).T

,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,99%,max
以摄氏度为单位的最低温度,99075.0,12.174983,6.403015,-8.2,-1.9,1.8,3.9,7.6,12.0,16.8,20.8,25.8,33.9
以摄氏度为单位的最高温度,99300.0,23.219216,7.118799,-4.8,9.0,12.9,14.5,17.9,22.6,28.2,32.9,40.2,48.1
当天记录的降雨量,98501.0,2.339207,8.418217,0.0,0.0,0.0,0.0,0.0,0.0,0.8,6.0,37.2,371.0
到早上9点之前的24小时的A级蒸发量,56850.0,5.473085,4.253592,0.0,0.4,1.0,1.4,2.6,4.8,7.4,10.2,18.6,145.0
白日受到日照的完整小时,51980.0,7.603459,3.786195,0.0,0.0,0.3,1.5,4.8,8.4,10.6,12.1,13.4,14.5
在到午夜12点前的24小时中的最强风速,93093.0,39.961297,13.572859,6.0,15.0,20.0,24.0,31.0,39.0,48.0,57.0,81.0,135.0
上午9点之前每个十分钟的风速的平均值,98609.0,13.991887,8.893245,0.0,0.0,0.0,4.0,7.0,13.0,19.0,26.0,39.0,130.0
下午3点之前每个十分钟的风速的平均值,97702.0,18.627787,8.789109,0.0,2.0,6.0,9.0,13.0,19.0,24.0,30.0,43.0,83.0
上午9点的湿度,98304.0,68.854523,19.065194,0.0,17.0,34.0,44.0,57.0,70.0,83.0,94.0,100.0,100.0
下午3点的湿度,96992.0,51.485813,20.816642,0.0,9.0,17.0,23.0,37.0,52.0,66.0,79.0,98.0,100.0
上午9点平均海平面上的大气压,89710.0,1017.656125,7.105493,980.5,1000.2,1006.2,1008.8,1013.0,1017.6,1022.4,1026.7,1033.9,1041.0
下午3点平均海平面上的大气压,89733.0,1015.265737,7.031277,978.2,998.5,1004.0,1006.4,1010.5,1015.2,1020.0,1024.3,1031.5,1038.5
上午9点的天空被云层遮蔽的程度,61837.0,4.441807,2.887625,0.0,0.0,0.0,1.0,1.0,5.0,7.0,8.0,8.0,8.0
下午3点的天空被云层遮蔽的程度,59465.0,4.508030,2.721434,0.0,0.0,0.0,1.0,2.0,5.0,7.0,8.0,8.0,9.0
上午9点的摄氏度温度,98908.0,16.977790,6.492127,-7.2,2.6,6.9,8.9,12.3,16.7,21.6,25.8,31.2,40.2
下午3点的摄氏度温度,97614.0,21.679544,6.939894,-5.4,7.6,11.5,13.3,16.6,21.1,26.4,31.2,38.5,46.7

In [17]:

xtest.describe([0.01,0.05,0.1,0.25,0.5,0.75,0.9,0.99]).T

,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,99%,max
以摄氏度为单位的最低温度,42481.0,12.213027,6.403902,-8.5,-1.80,1.8,4.0,7.6,12.0,16.9,20.8,25.800,31.9
以摄氏度为单位的最高温度,42571.0,23.244439,7.114916,-3.8,9.30,12.8,14.5,18.0,22.6,28.3,33.0,40.100,47.0
当天记录的降雨量,42286.0,2.375056,8.573603,0.0,0.00,0.0,0.0,0.0,0.0,0.6,6.2,37.630,278.4
到早上9点之前的24小时的A级蒸发量,24500.0,5.462257,4.033615,0.0,0.40,1.0,1.4,2.6,4.8,7.4,10.2,18.000,68.8
白日受到日照的完整小时,22397.0,7.674506,3.770282,0.0,0.00,0.4,1.6,4.9,8.5,10.7,12.1,13.400,14.1
在到午夜12点前的24小时中的最强风速,39830.0,40.038037,13.626007,7.0,15.00,20.0,24.0,31.0,39.0,48.0,57.0,80.000,135.0
上午9点之前每个十分钟的风速的平均值,42236.0,14.025571,8.893613,0.0,0.00,0.0,4.0,7.0,13.0,19.0,26.0,39.000,87.0
下午3点之前每个十分钟的风速的平均值,41861.0,18.660424,8.836544,0.0,2.00,6.0,9.0,13.0,19.0,24.0,30.0,43.000,87.0
上午9点的湿度,42115.0,68.818806,19.019007,1.0,17.00,34.0,44.0,57.0,70.0,83.0,94.0,100.000,100.0
下午3点的湿度,41591.0,51.475127,20.753946,0.0,9.00,16.0,23.0,37.0,52.0,66.0,79.0,97.000,100.0
上午9点平均海平面上的大气压,38469.0,1017.648239,7.105524,982.9,1000.30,1006.2,1008.8,1012.9,1017.6,1022.4,1026.7,1034.132,1040.9
下午3点平均海平面上的大气压,38479.0,1015.240635,7.049312,977.1,998.60,1004.0,1006.4,1010.4,1015.2,1020.0,1024.3,1031.800,1039.6
上午9点的天空被云层遮蔽的程度,26699.0,4.426495,2.885630,0.0,0.00,0.0,1.0,1.0,5.0,7.0,8.0,8.000,9.0
下午3点的天空被云层遮蔽的程度,25634.0,4.491886,2.718792,0.0,0.00,0.0,1.0,2.0,5.0,7.0,8.0,8.000,8.0
上午9点的摄氏度温度,42381.0,17.010189,6.494518,-5.9,2.58,7.0,9.0,12.3,16.7,21.6,25.9,31.300,38.9
下午3点的摄氏度温度,41853.0,21.705173,6.932276,-5.1,7.90,11.6,13.2,16.6,21.1,26.5,31.2,38.400,46.1

In [18]:
# 1/如果异常值只出现了一次，多半是输入错误，直接把异常值删除
# 2/如果异常值出现了多次，去跟业务人员沟通，可能这是某种特殊表示，如果是人为造成的错误，异常值留着是没有用
# 的，只要数据量不是太大，都可以删除
# 3/如果异常值占到你总数据量的10%以上了，不能轻易删除。可以考虑把异常值替换成非异常但是非干扰的项，比如说用0
# 来进行替换，或者把异常当缺失值，用均值或者众数来进行替换
xtrain.loc[xtrain.loc[:,"下午3点的天空被云层遮蔽的程度"] >= 9,"下午3点的天空被云层遮蔽的程度"]

74504    9.0
Name: 下午3点的天空被云层遮蔽的程度, dtype: float64

In [19]:
xtest.loc[xtest.loc[:,"上午9点的天空被云层遮蔽的程度"] >= 9,"上午9点的天空被云层遮蔽的程度"]

20890    9.0
22448    9.0
Name: 上午9点的天空被云层遮蔽的程度, dtype: float64

In [20]:
xtrain = xtrain.drop(index=74504)
xtest = xtest.drop(index=[20890,22448])

In [21]:
ytrain = ytrain.drop(index=74504)
ytest = ytest.drop(index=[20890,22448])

In [22]:
xtrain.shape,xtest.shape,ytrain.shape,ytest.shape

((99534, 21), (42656, 21), (99534, 1), (42656, 1))

In [23]:
for i in [xtrain, xtest, ytrain, ytest]:
    i.index = range(i.shape[0])

In [24]:
xtrainc = xtrain.copy()

In [25]:
xtrainc.sort_values(by="获取该信息的气象站的名称")

,观察日期,获取该信息的气象站的名称,以摄氏度为单位的最低温度,以摄氏度为单位的最高温度,当天记录的降雨量,到早上9点之前的24小时的A级蒸发量,白日受到日照的完整小时,在到午夜12点前的24小时中的最强风的风向,在到午夜12点前的24小时中的最强风速,上午9点时的风向,...,上午9点之前每个十分钟的风速的平均值,下午3点之前每个十分钟的风速的平均值,上午9点的湿度,下午3点的湿度,上午9点平均海平面上的大气压,下午3点平均海平面上的大气压,上午9点的天空被云层遮蔽的程度,下午3点的天空被云层遮蔽的程度,上午9点的摄氏度温度,下午3点的摄氏度温度
82857,2011-06-30,Adelaide,14.7,19.9,0.0,2.4,0.9,NNE,31.0,NNE,...,15.0,11.0,53.0,49.0,1028.7,1025.8,NaN,NaN,16.9,18.7
11201,2012-06-24,Adelaide,7.6,16.1,1.6,NaN,NaN,WNW,30.0,NE,...,7.0,17.0,94.0,69.0,1033.3,1032.2,NaN,NaN,11.0,14.8
35591,2011-07-23,Adelaide,5.7,17.5,NaN,NaN,4.3,WNW,28.0,NE,...,7.0,13.0,62.0,44.0,1022.3,1020.1,NaN,NaN,10.0,16.7
97239,2013-11-26,Adelaide,19.8,35.9,0.0,8.0,9.7,W,30.0,NNE,...,11.0,9.0,18.0,13.0,1011.9,1009.2,NaN,NaN,25.9,33.6
83714,2010-03-30,Adelaide,13.5,24.2,0.0,4.6,10.1,ESE,30.0,SE,...,9.0,15.0,71.0,36.0,1024.6,1022.3,NaN,NaN,16.5,23.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79009,2010-02-23,Woomera,17.6,32.8,0.0,8.6,12.4,SE,43.0,SSE,...,20.0,11.0,58.0,29.0,1018.8,1016.6,1.0,1.0,20.3,30.5
36114,2012-03-15,Woomera,15.6,27.8,1.6,16.6,NaN,SW,48.0,SSW,...,22.0,15.0,61.0,35.0,1009.1,1007.6,0.0,0.0,17.9,25.0
28106,2015-11-24,Woomera,14.2,34.4,0.0,9.4,NaN,NNW,37.0,ESE,...,17.0,9.0,38.0,9.0,1017.9,1013.3,0.0,0.0,21.8,32.3
90448,2015-03-24,Woomera,11.8,23.2,0.0,15.8,NaN,S,48.0,SSW,...,26.0,22.0,59.0,26.0,1021.5,1019.3,0.0,0.0,13.4,21.2
42481,2010-06-11,Woomera,6.0,16.0,0.0,2.2,6.8,SSE,28.0,SW,...,7.0,15.0,89.0,40.0,1030.2,1027.9,5.0,7.0,8.5,15.3

In [26]:
# 先处理困难特征
xtrain.loc[:,'观察日期'].value_counts().count()

3399

In [27]:
colums_dict

{'Date': '观察日期',
 'Location': '获取该信息的气象站的名称',
 'MinTemp': '以摄氏度为单位的最低温度',
 'MaxTemp': '以摄氏度为单位的最高温度',
 'Rainfall': '当天记录的降雨量',
 'Evaporation': '到早上9点之前的24小时的A级蒸发量',
 'Sunshine': '白日受到日照的完整小时',
 'WindGustDir': '在到午夜12点前的24小时中的最强风的风向',
 'WindGustSpeed': '在到午夜12点前的24小时中的最强风速',
 'WindDir9am': '上午9点时的风向',
 'WindDir3pm': '下午3点时的风向',
 'WindSpeed9am': '上午9点之前每个十分钟的风速的平均值',
 'WindSpeed3pm': '下午3点之前每个十分钟的风速的平均值',
 'Humidity9am': '上午9点的湿度',
 'Humidity3pm': '下午3点的湿度',
 'Pressure9am': '上午9点平均海平面上的大气压',
 'Pressure3pm': '下午3点平均海平面上的大气压',
 'Cloud9am': '上午9点的天空被云层遮蔽的程度',
 'Cloud3pm': '下午3点的天空被云层遮蔽的程度',
 'Temp9am': '上午9点的摄氏度温度',
 'Temp3pm': '下午3点的摄氏度温度',
 'RainTomorrow': '目标变量'}

In [28]:
xtrain.loc[xtrain.loc[:,"当天记录的降雨量"] >= 1,"RainToday"] = "yes"
xtrain.loc[xtrain.loc[:,"当天记录的降雨量"] < 1,"RainToday"] = "no"
xtrain.loc[xtrain.loc[:,"当天记录的降雨量"] == np.nan,"RainToday"] = np.nan

In [29]:
xtest.loc[xtest.loc[:,"当天记录的降雨量"] >= 1,"RainToday"] = "yes"
xtest.loc[xtest.loc[:,"当天记录的降雨量"] < 1,"RainToday"] = "no"
xtest.loc[xtest.loc[:,"当天记录的降雨量"] == np.nan,"RainToday"] = np.nan

In [30]:
xtrain['month'] = xtrain['观察日期'].apply(lambda x :x.month)
xtest['month'] = xtest['观察日期'].apply(lambda x :x.month)

In [31]:
xtrain.head()

,观察日期,获取该信息的气象站的名称,以摄氏度为单位的最低温度,以摄氏度为单位的最高温度,当天记录的降雨量,到早上9点之前的24小时的A级蒸发量,白日受到日照的完整小时,在到午夜12点前的24小时中的最强风的风向,在到午夜12点前的24小时中的最强风速,上午9点时的风向,...,上午9点的湿度,下午3点的湿度,上午9点平均海平面上的大气压,下午3点平均海平面上的大气压,上午9点的天空被云层遮蔽的程度,下午3点的天空被云层遮蔽的程度,上午9点的摄氏度温度,下午3点的摄氏度温度,RainToday,month
0,2009-07-31,Perth,3.8,21.1,0.0,2.4,9.7,SSW,19.0,NaN,...,74.0,38.0,1026.9,1023.9,1.0,0.0,11.7,20.2,no,7
1,2011-10-09,NorahHead,13.7,23.5,0.2,NaN,NaN,WSW,31.0,WNW,...,81.0,39.0,1008.6,1004.9,NaN,NaN,17.1,22.6,no,10
2,2011-10-25,Hobart,2.8,16.5,2.2,3.4,11.1,SW,41.0,NNW,...,55.0,41.0,1018.2,1016.9,NaN,NaN,8.7,15.6,yes,10
3,2010-12-19,PearceRAAF,15.0,29.0,NaN,NaN,5.7,ESE,59.0,E,...,35.0,20.0,1012.0,1008.4,NaN,NaN,22.3,28.5,NaN,12
4,2016-02-05,Albany,16.3,32.0,0.0,5.4,12.9,NaN,NaN,E,...,80.0,NaN,1015.5,1014.7,0.0,NaN,21.0,NaN,no,2

In [32]:
xtrain.drop(['观察日期'],axis=1,inplace=True)

In [33]:
xtest.drop(['观察日期'],axis=1,inplace=True)

In [34]:
cityll = pd.read_csv(r"G:\机器学习资料\菜菜的skleran\08支持向量机下\cityll.csv",index_col=0)
city_climate = pd.read_csv(r"G:\机器学习资料\菜菜的skleran\08支持向量机下\Cityclimate.csv")

In [35]:
cityll.head()

           City  Latitude  Longitude Latitudedir Longitudedir
0      Adelaide  34.9285°  138.6007°          S,            E
1        Albany  35.0275°  117.8840°          S,            E
2        Albury  36.0737°  146.9135°          S,            E
3       Wodonga  36.1241°  146.8818°          S,            E
4  AliceSprings  23.6980°  133.8807°          S,            E

In [36]:
xtrain.loc[:,'获取该信息的气象站的名称'].value_counts().count()

49

In [37]:
city_climate.head()

           City                      Climate
0      Adelaide            Warm temperate
1        Albany            Mild temperate
2        Albury  Hot dry summer, cool winter
3       Wodonga  Hot dry summer, cool winter
4  AliceSprings  Hot dry summer, warm winter

In [38]:
cityll["Latitudenum"] = cityll["Latitude"].apply(lambda x:float(x[:-1]))
cityll["Longitudenum"] = cityll["Longitude"].apply(lambda x:float(x[:-1]))

In [39]:
citylld = cityll.iloc[:,[0,5,6]]
citylld.head()

           City  Latitudenum  Longitudenum
0      Adelaide      34.9285      138.6007
1        Albany      35.0275      117.8840
2        Albury      36.0737      146.9135
3       Wodonga      36.1241      146.8818
4  AliceSprings      23.6980      133.8807

In [40]:
citylld["climate"] = city_climate.iloc[:,-1]

D:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [41]:
citylld['climate'].value_counts()

Hot dry summer, cool winter          24
Hot dry summer, warm winter          18
Warm temperate                       18
High humidity summer, warm winter    17
Mild temperate                        9
Cool temperate                        9
Warm humid summer, mild winter        5
Name: climate, dtype: int64

In [42]:
samplecity = pd.read_csv(r"G:\机器学习资料\菜菜的skleran\08支持向量机下\samplecity.csv",index_col=0)
samplecity.head()

       City  Latitude  Longitude Latitudedir Longitudedir
0  Canberra  35.2809°  149.1300°          S,            E
1    Sydney  33.8688°  151.2093°          S,            E
2     Perth  31.9505°  115.8605°          S,            E
3    Darwin  12.4634°  130.8456°          S,            E
4    Hobart  42.8821°  147.3272°          S,            E

In [43]:
samplecity["Latitudenum"] = samplecity["Latitude"].apply(lambda x:float(x[:-1]))
samplecity["Longitudenum"] = samplecity["Longitude"].apply(lambda x:float(x[:-1]))
samplecityd = samplecity.iloc[:,[0,5,6]]
samplecityd.head()

       City  Latitudenum  Longitudenum
0  Canberra      35.2809      149.1300
1    Sydney      33.8688      151.2093
2     Perth      31.9505      115.8605
3    Darwin      12.4634      130.8456
4    Hobart      42.8821      147.3272

In [44]:
from math import radians,sin,cos,acos

citylld.loc[:,"slat"] = citylld.iloc[:,1].apply(lambda x : radians(x))
citylld.loc[:,"slon"] = citylld.iloc[:,2].apply(lambda x : radians(x))
samplecityd.loc[:,"elat"] = samplecityd.iloc[:,1].apply(lambda x : radians(x))
samplecityd.loc[:,"elon"] = samplecityd.iloc[:,2].apply(lambda x : radians(x))

D:\anaconda3\lib\site-packages\pandas\core\indexing.py:844: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
D:\anaconda3\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [45]:
samplecityd.head()

       City  Latitudenum  Longitudenum      elat      elon
0  Canberra      35.2809      149.1300  0.615768  2.602810
1    Sydney      33.8688      151.2093  0.591122  2.639100
2     Perth      31.9505      115.8605  0.557641  2.022147
3    Darwin      12.4634      130.8456  0.217527  2.283687
4    Hobart      42.8821      147.3272  0.748434  2.571345

In [46]:
import sys
for i in range(samplecityd.shape[0]):
    slat = citylld.loc[:,"slat"]
    slon = citylld.loc[:,"slon"]
    elat = samplecityd.loc[i,"elat"]
    elon = samplecityd.loc[i,"elon"]
    dist = 6371.01 * np.arccos(np.sin(slat)*np.sin(elat) +
                          np.cos(slat)*np.cos(elat)*np.cos(slon.values - elon))
    city_index = np.argsort(dist)[0]
    #每次计算后，取距离最近的城市，然后将最近的城市和城市对应的气候都匹配到samplecityd中
    samplecityd.loc[i,"closest_city"] = citylld.loc[city_index,"City"]
    samplecityd.loc[i,"climate"] = citylld.loc[city_index,"climate"]

D:\anaconda3\lib\site-packages\pandas\core\indexing.py:844: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
D:\anaconda3\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
D:\anaconda3\lib\site-packages\pandas\core\series.py:679: RuntimeWarning: invalid value encountered in arccos
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [47]:
samplecityd.head()

,City,Latitudenum,Longitudenum,elat,elon,closest_city,climate
0,Canberra,35.2809,149.1300,0.615768,2.602810,Canberra,Cool temperate
1,Sydney,33.8688,151.2093,0.591122,2.639100,Sydney,Warm temperate
2,Perth,31.9505,115.8605,0.557641,2.022147,Perth,Warm temperate
3,Darwin,12.4634,130.8456,0.217527,2.283687,Darwin,"High humidity summer, warm winter"
4,Hobart,42.8821,147.3272,0.748434,2.571345,Hobart,Cool temperate

In [48]:
samplecityd["climate"].value_counts()

Warm temperate                       15
Mild temperate                       10
Cool temperate                        9
Hot dry summer, cool winter           6
High humidity summer, warm winter     4
Hot dry summer, warm winter           3
Warm humid summer, mild winter        2
Name: climate, dtype: int64

In [49]:
locafinal = samplecityd.iloc[:,[0,-1]]

In [50]:
locafinal.head()

       City                            climate
0  Canberra                  Cool temperate
1    Sydney                  Warm temperate
2     Perth                  Warm temperate
3    Darwin  High humidity summer, warm winter
4    Hobart                  Cool temperate

In [51]:
locafinal.columns = ["Location","Climate"]

In [52]:
locafinal = locafinal.set_index(keys="Location")

In [53]:
locafinal.head()

                                    Climate
Location
Canberra                  Cool temperate
Sydney                    Warm temperate
Perth                     Warm temperate
Darwin    High humidity summer, warm winter
Hobart                    Cool temperate

In [54]:
colums_dict

{'Date': '观察日期',
 'Location': '获取该信息的气象站的名称',
 'MinTemp': '以摄氏度为单位的最低温度',
 'MaxTemp': '以摄氏度为单位的最高温度',
 'Rainfall': '当天记录的降雨量',
 'Evaporation': '到早上9点之前的24小时的A级蒸发量',
 'Sunshine': '白日受到日照的完整小时',
 'WindGustDir': '在到午夜12点前的24小时中的最强风的风向',
 'WindGustSpeed': '在到午夜12点前的24小时中的最强风速',
 'WindDir9am': '上午9点时的风向',
 'WindDir3pm': '下午3点时的风向',
 'WindSpeed9am': '上午9点之前每个十分钟的风速的平均值',
 'WindSpeed3pm': '下午3点之前每个十分钟的风速的平均值',
 'Humidity9am': '上午9点的湿度',
 'Humidity3pm': '下午3点的湿度',
 'Pressure9am': '上午9点平均海平面上的大气压',
 'Pressure3pm': '下午3点平均海平面上的大气压',
 'Cloud9am': '上午9点的天空被云层遮蔽的程度',
 'Cloud3pm': '下午3点的天空被云层遮蔽的程度',
 'Temp9am': '上午9点的摄氏度温度',
 'Temp3pm': '下午3点的摄氏度温度',
 'RainTomorrow': '目标变量'}

In [55]:
import re
xtrain["Location"] = xtrain["获取该信息的气象站的名称"].map(locafinal.iloc[:,0]).apply(lambda x:re.sub(",","",x.strip()))
xtest["Location"] = xtest["获取该信息的气象站的名称"].map(locafinal.iloc[:,0]).apply(lambda x:re.sub(",","",x.strip()))

In [56]:
xtrain.head()

,获取该信息的气象站的名称,以摄氏度为单位的最低温度,以摄氏度为单位的最高温度,当天记录的降雨量,到早上9点之前的24小时的A级蒸发量,白日受到日照的完整小时,在到午夜12点前的24小时中的最强风的风向,在到午夜12点前的24小时中的最强风速,上午9点时的风向,下午3点时的风向,...,下午3点的湿度,上午9点平均海平面上的大气压,下午3点平均海平面上的大气压,上午9点的天空被云层遮蔽的程度,下午3点的天空被云层遮蔽的程度,上午9点的摄氏度温度,下午3点的摄氏度温度,RainToday,month,Location
0,Perth,3.8,21.1,0.0,2.4,9.7,SSW,19.0,NaN,S,...,38.0,1026.9,1023.9,1.0,0.0,11.7,20.2,no,7,Warm temperate
1,NorahHead,13.7,23.5,0.2,NaN,NaN,WSW,31.0,WNW,W,...,39.0,1008.6,1004.9,NaN,NaN,17.1,22.6,no,10,Cool temperate
2,Hobart,2.8,16.5,2.2,3.4,11.1,SW,41.0,NNW,SE,...,41.0,1018.2,1016.9,NaN,NaN,8.7,15.6,yes,10,Cool temperate
3,PearceRAAF,15.0,29.0,NaN,NaN,5.7,ESE,59.0,E,ESE,...,20.0,1012.0,1008.4,NaN,NaN,22.3,28.5,NaN,12,Warm temperate
4,Albany,16.3,32.0,0.0,5.4,12.9,NaN,NaN,E,NaN,...,NaN,1015.5,1014.7,0.0,NaN,21.0,NaN,no,2,Mild temperate

In [57]:
xtrain = xtrain.rename(columns={"Location":"Climate"})
xtest = xtest.rename(columns={"Location":"Climate"})

In [58]:
xtrain.drop(['获取该信息的气象站的名称'],axis=1,inplace=True)
xtest.drop(['获取该信息的气象站的名称'],axis=1,inplace=True)

In [59]:
xtrain.head()

,以摄氏度为单位的最低温度,以摄氏度为单位的最高温度,当天记录的降雨量,到早上9点之前的24小时的A级蒸发量,白日受到日照的完整小时,在到午夜12点前的24小时中的最强风的风向,在到午夜12点前的24小时中的最强风速,上午9点时的风向,下午3点时的风向,上午9点之前每个十分钟的风速的平均值,...,下午3点的湿度,上午9点平均海平面上的大气压,下午3点平均海平面上的大气压,上午9点的天空被云层遮蔽的程度,下午3点的天空被云层遮蔽的程度,上午9点的摄氏度温度,下午3点的摄氏度温度,RainToday,month,Climate
0,3.8,21.1,0.0,2.4,9.7,SSW,19.0,NaN,S,0.0,...,38.0,1026.9,1023.9,1.0,0.0,11.7,20.2,no,7,Warm temperate
1,13.7,23.5,0.2,NaN,NaN,WSW,31.0,WNW,W,7.0,...,39.0,1008.6,1004.9,NaN,NaN,17.1,22.6,no,10,Cool temperate
2,2.8,16.5,2.2,3.4,11.1,SW,41.0,NNW,SE,19.0,...,41.0,1018.2,1016.9,NaN,NaN,8.7,15.6,yes,10,Cool temperate
3,15.0,29.0,NaN,NaN,5.7,ESE,59.0,E,ESE,30.0,...,20.0,1012.0,1008.4,NaN,NaN,22.3,28.5,NaN,12,Warm temperate
4,16.3,32.0,0.0,5.4,12.9,NaN,NaN,E,NaN,4.0,...,NaN,1015.5,1014.7,0.0,NaN,21.0,NaN,no,2,Mild temperate

In [60]:
xtest.head()

,以摄氏度为单位的最低温度,以摄氏度为单位的最高温度,当天记录的降雨量,到早上9点之前的24小时的A级蒸发量,白日受到日照的完整小时,在到午夜12点前的24小时中的最强风的风向,在到午夜12点前的24小时中的最强风速,上午9点时的风向,下午3点时的风向,上午9点之前每个十分钟的风速的平均值,...,下午3点的湿度,上午9点平均海平面上的大气压,下午3点平均海平面上的大气压,上午9点的天空被云层遮蔽的程度,下午3点的天空被云层遮蔽的程度,上午9点的摄氏度温度,下午3点的摄氏度温度,RainToday,month,Climate
0,7.1,13.0,8.8,NaN,NaN,N,41.0,N,WNW,24.0,...,98.0,1001.7,1005.4,8.0,8.0,8.6,11.5,yes,6,Cool temperate
1,13.2,18.3,0.0,NaN,NaN,E,48.0,ESE,ESE,24.0,...,73.0,1027.6,1023.8,NaN,NaN,14.2,17.0,no,10,Mild temperate
2,9.2,22.7,0.0,5.0,11.1,ENE,52.0,ENE,ESE,26.0,...,25.0,1030.1,1025.9,0.0,0.0,15.1,22.5,no,9,Warm temperate
3,15.3,26.1,0.0,10.4,NaN,E,44.0,E,NE,24.0,...,40.0,1013.2,1009.8,7.0,7.0,17.5,24.3,no,12,Hot dry summer cool winter
4,11.9,31.8,0.0,5.0,4.1,NW,72.0,E,N,6.0,...,25.0,1006.7,1001.0,7.0,6.0,16.2,27.4,no,3,Mild temperate

In [61]:
xtrain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99534 entries, 0 to 99533
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   以摄氏度为单位的最低温度           99074 non-null  float64
 1   以摄氏度为单位的最高温度           99299 non-null  float64
 2   当天记录的降雨量               98500 non-null  float64
 3   到早上9点之前的24小时的A级蒸发量     56849 non-null  float64
 4   白日受到日照的完整小时            51979 non-null  float64
 5   在到午夜12点前的24小时中的最强风的风向  93045 non-null  object
 6   在到午夜12点前的24小时中的最强风速    93092 non-null  float64
 7   上午9点时的风向               92516 non-null  object
 8   下午3点时的风向               96900 non-null  object
 9   上午9点之前每个十分钟的风速的平均值     98608 non-null  float64
 10  下午3点之前每个十分钟的风速的平均值     97701 non-null  float64
 11  上午9点的湿度                98303 non-null  float64
 12  下午3点的湿度                96991 non-null  float64
 13  上午9点平均海平面上的大气压         89709 non-null  float64
 14  下午3点平均海平面上的大气压         89732 non-null  float64
 15  上午9点的天空被云层遮蔽的程度        61836 non-null  float64
 16  下午3点的天空被云层遮蔽的程度        59464 non-null  float64
 17  上午9点的摄氏度温度             98907 non-null  float64
 18  下午3点的摄氏度温度             97613 non-null  float64
 19  RainToday              98500 non-null  object
 20  month                  99534 non-null  int64
 21  Climate                99534 non-null  object
dtypes: float64(16), int64(1), object(5)
memory usage: 16.7+ MB

In [62]:
cate = xtrain.columns[xtrain.dtypes == "object"].tolist()
cate

['在到午夜12点前的24小时中的最强风的风向', '上午9点时的风向', '下午3点时的风向', 'RainToday', 'Climate']

In [63]:
cloud = ["上午9点的天空被云层遮蔽的程度","下午3点的天空被云层遮蔽的程度"]
cate = cate + cloud

In [64]:
cate

['在到午夜12点前的24小时中的最强风的风向',
 '上午9点时的风向',
 '下午3点时的风向',
 'RainToday',
 'Climate',
 '上午9点的天空被云层遮蔽的程度',
 '下午3点的天空被云层遮蔽的程度']

In [65]:
from sklearn.impute import SimpleImputer

In [66]:
si = SimpleImputer(missing_values=np.nan,strategy='most_frequent')

In [67]:
si.fit(xtrain.loc[:,cate])

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='most_frequent', verbose=0)

In [68]:
xtrain.loc[:,cate] = si.transform(xtrain.loc[:,cate])
xtest.loc[:,cate] = si.transform(xtest.loc[:,cate])

In [69]:
xtrain.head()

,以摄氏度为单位的最低温度,以摄氏度为单位的最高温度,当天记录的降雨量,到早上9点之前的24小时的A级蒸发量,白日受到日照的完整小时,在到午夜12点前的24小时中的最强风的风向,在到午夜12点前的24小时中的最强风速,上午9点时的风向,下午3点时的风向,上午9点之前每个十分钟的风速的平均值,...,下午3点的湿度,上午9点平均海平面上的大气压,下午3点平均海平面上的大气压,上午9点的天空被云层遮蔽的程度,下午3点的天空被云层遮蔽的程度,上午9点的摄氏度温度,下午3点的摄氏度温度,RainToday,month,Climate
0,3.8,21.1,0.0,2.4,9.7,SSW,19.0,N,S,0.0,...,38.0,1026.9,1023.9,1.0,0.0,11.7,20.2,no,7,Warm temperate
1,13.7,23.5,0.2,NaN,NaN,WSW,31.0,WNW,W,7.0,...,39.0,1008.6,1004.9,7.0,7.0,17.1,22.6,no,10,Cool temperate
2,2.8,16.5,2.2,3.4,11.1,SW,41.0,NNW,SE,19.0,...,41.0,1018.2,1016.9,7.0,7.0,8.7,15.6,yes,10,Cool temperate
3,15.0,29.0,NaN,NaN,5.7,ESE,59.0,E,ESE,30.0,...,20.0,1012.0,1008.4,7.0,7.0,22.3,28.5,no,12,Warm temperate
4,16.3,32.0,0.0,5.4,12.9,W,NaN,E,SE,4.0,...,NaN,1015.5,1014.7,0.0,7.0,21.0,NaN,no,2,Mild temperate

In [70]:
xtest.head()

,以摄氏度为单位的最低温度,以摄氏度为单位的最高温度,当天记录的降雨量,到早上9点之前的24小时的A级蒸发量,白日受到日照的完整小时,在到午夜12点前的24小时中的最强风的风向,在到午夜12点前的24小时中的最强风速,上午9点时的风向,下午3点时的风向,上午9点之前每个十分钟的风速的平均值,...,下午3点的湿度,上午9点平均海平面上的大气压,下午3点平均海平面上的大气压,上午9点的天空被云层遮蔽的程度,下午3点的天空被云层遮蔽的程度,上午9点的摄氏度温度,下午3点的摄氏度温度,RainToday,month,Climate
0,7.1,13.0,8.8,NaN,NaN,N,41.0,N,WNW,24.0,...,98.0,1001.7,1005.4,8.0,8.0,8.6,11.5,yes,6,Cool temperate
1,13.2,18.3,0.0,NaN,NaN,E,48.0,ESE,ESE,24.0,...,73.0,1027.6,1023.8,7.0,7.0,14.2,17.0,no,10,Mild temperate
2,9.2,22.7,0.0,5.0,11.1,ENE,52.0,ENE,ESE,26.0,...,25.0,1030.1,1025.9,0.0,0.0,15.1,22.5,no,9,Warm temperate
3,15.3,26.1,0.0,10.4,NaN,E,44.0,E,NE,24.0,...,40.0,1013.2,1009.8,7.0,7.0,17.5,24.3,no,12,Hot dry summer cool winter
4,11.9,31.8,0.0,5.0,4.1,NW,72.0,E,N,6.0,...,25.0,1006.7,1001.0,7.0,6.0,16.2,27.4,no,3,Mild temperate

In [71]:
xtrain.loc[:,cate].isnull().mean()

在到午夜12点前的24小时中的最强风的风向    0.0
上午9点时的风向                 0.0
下午3点时的风向                 0.0
RainToday                0.0
Climate                  0.0
上午9点的天空被云层遮蔽的程度          0.0
下午3点的天空被云层遮蔽的程度          0.0
dtype: float64

In [72]:
xtest.loc[:,cate].isnull().mean()

在到午夜12点前的24小时中的最强风的风向    0.0
上午9点时的风向                 0.0
下午3点时的风向                 0.0
RainToday                0.0
Climate                  0.0
上午9点的天空被云层遮蔽的程度          0.0
下午3点的天空被云层遮蔽的程度          0.0
dtype: float64

In [73]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()

In [74]:
oe = oe.fit(xtrain.loc[:,cate])

In [75]:
xtrain.loc[:,cate] = oe.transform(xtrain.loc[:,cate])
xtest.loc[:,cate] = oe.transform(xtest.loc[:,cate])
xtrain.loc[:,cate].head()
xtest.loc[:,cate].head()

,在到午夜12点前的24小时中的最强风的风向,上午9点时的风向,下午3点时的风向,RainToday,Climate,上午9点的天空被云层遮蔽的程度,下午3点的天空被云层遮蔽的程度
0,3.0,3.0,14.0,1.0,0.0,8.0,8.0
1,0.0,2.0,2.0,0.0,4.0,7.0,7.0
2,1.0,1.0,2.0,0.0,6.0,0.0,0.0
3,0.0,0.0,4.0,0.0,2.0,7.0,7.0
4,7.0,0.0,3.0,0.0,4.0,7.0,6.0

In [76]:
col = [i for i in xtrain.columns.tolist() if i not in cate ]
col

['以摄氏度为单位的最低温度',
 '以摄氏度为单位的最高温度',
 '当天记录的降雨量',
 '到早上9点之前的24小时的A级蒸发量',
 '白日受到日照的完整小时',
 '在到午夜12点前的24小时中的最强风速',
 '上午9点之前每个十分钟的风速的平均值',
 '下午3点之前每个十分钟的风速的平均值',
 '上午9点的湿度',
 '下午3点的湿度',
 '上午9点平均海平面上的大气压',
 '下午3点平均海平面上的大气压',
 '上午9点的摄氏度温度',
 '下午3点的摄氏度温度',
 'month']

In [77]:
impmean = SimpleImputer(missing_values=np.nan,strategy='mean')
impmean = impmean.fit(xtrain.loc[:,col])
xtrain.loc[:,col] = impmean.transform(xtrain.loc[:,col])
xtest.loc[:,col] = impmean.transform(xtest.loc[:,col])

In [78]:
xtrain.head()

,以摄氏度为单位的最低温度,以摄氏度为单位的最高温度,当天记录的降雨量,到早上9点之前的24小时的A级蒸发量,白日受到日照的完整小时,在到午夜12点前的24小时中的最强风的风向,在到午夜12点前的24小时中的最强风速,上午9点时的风向,下午3点时的风向,上午9点之前每个十分钟的风速的平均值,...,下午3点的湿度,上午9点平均海平面上的大气压,下午3点平均海平面上的大气压,上午9点的天空被云层遮蔽的程度,下午3点的天空被云层遮蔽的程度,上午9点的摄氏度温度,下午3点的摄氏度温度,RainToday,month,Climate
0,3.8,21.1,0.000000,2.400000,9.700000,11.0,19.000000,3.0,8.0,0.0,...,38.00000,1026.9,1023.9,1.0,0.0,11.7,20.200000,0.0,7.0,6.0
1,13.7,23.5,0.200000,5.472978,7.603386,15.0,31.000000,14.0,13.0,7.0,...,39.00000,1008.6,1004.9,7.0,7.0,17.1,22.600000,0.0,10.0,0.0
2,2.8,16.5,2.200000,3.400000,11.100000,12.0,41.000000,6.0,9.0,19.0,...,41.00000,1018.2,1016.9,7.0,7.0,8.7,15.600000,1.0,10.0,0.0
3,15.0,29.0,2.339228,5.472978,5.700000,2.0,59.000000,0.0,2.0,30.0,...,20.00000,1012.0,1008.4,7.0,7.0,22.3,28.500000,0.0,12.0,6.0
4,16.3,32.0,0.000000,5.400000,12.900000,13.0,39.961307,0.0,9.0,4.0,...,51.48621,1015.5,1014.7,0.0,7.0,21.0,21.679523,0.0,2.0,4.0

In [79]:
xtest.loc[:,col].isna().mean()

以摄氏度为单位的最低温度           0.0
以摄氏度为单位的最高温度           0.0
当天记录的降雨量               0.0
到早上9点之前的24小时的A级蒸发量     0.0
白日受到日照的完整小时            0.0
在到午夜12点前的24小时中的最强风速    0.0
上午9点之前每个十分钟的风速的平均值     0.0
下午3点之前每个十分钟的风速的平均值     0.0
上午9点的湿度                0.0
下午3点的湿度                0.0
上午9点平均海平面上的大气压         0.0
下午3点平均海平面上的大气压         0.0
上午9点的摄氏度温度             0.0
下午3点的摄氏度温度             0.0
month                  0.0
dtype: float64

In [80]:
col.remove("month")

In [81]:
from sklearn.preprocessing import StandardScaler

In [82]:
ss = StandardScaler()

In [83]:
ss = ss.fit(xtrain.loc[:,col])
xtrain.loc[:,col] = ss.transform(xtrain.loc[:,col])
xtest.loc[:,col] = ss.transform(xtest.loc[:,col])

In [84]:
xtrain.head()
xtest.head()

,以摄氏度为单位的最低温度,以摄氏度为单位的最高温度,当天记录的降雨量,到早上9点之前的24小时的A级蒸发量,白日受到日照的完整小时,在到午夜12点前的24小时中的最强风的风向,在到午夜12点前的24小时中的最强风速,上午9点时的风向,下午3点时的风向,上午9点之前每个十分钟的风速的平均值,...,下午3点的湿度,上午9点平均海平面上的大气压,下午3点平均海平面上的大气压,上午9点的天空被云层遮蔽的程度,下午3点的天空被云层遮蔽的程度,上午9点的摄氏度温度,下午3点的摄氏度温度,RainToday,month,Climate
0,-0.794433,-1.437221,0.771493,2.762973e-16,0.000000,3.0,0.079131,3.0,14.0,1.130657,...,2.263595,-2.365378,-1.477772,8.0,8.0,-1.294542,-1.481176,1.0,6.0,0.0
1,0.160452,-0.691833,-0.279332,2.762973e-16,0.000000,0.0,0.612412,2.0,2.0,1.130657,...,1.046969,1.474110,1.278332,7.0,7.0,-0.429228,-0.680896,0.0,10.0,4.0
2,-0.465702,-0.073020,-0.279332,-1.471353e-01,1.277970,1.0,0.917144,1.0,2.0,1.356602,...,-1.288952,1.844717,1.592888,0.0,0.0,-0.290160,0.119384,0.0,9.0,6.0
3,0.489183,0.405153,-0.279332,1.532713e+00,0.000000,0.0,0.307680,0.0,4.0,1.130657,...,-0.558977,-0.660586,-0.818703,7.0,7.0,0.080689,0.381294,0.0,12.0,2.0
4,-0.043048,1.206797,-0.279332,-1.471353e-01,-1.280445,7.0,2.440805,0.0,3.0,-0.902851,...,-1.288952,-1.624164,-2.136840,7.0,6.0,-0.120188,0.832361,0.0,3.0,4.0

In [85]:
ytrain.head()
ytest.head()

   0
0  1
1  0
2  0
3  0
4  1

In [86]:
from time import time
import datetime
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.metrics import roc_auc_score, recall_score

In [100]:
clf.decision_function(xtest)

array([ 1.34266358, -0.65622457, -1.23374979, ..., -1.33552176,
       -0.37616145, -1.22582214])

In [104]:
times = time()
print(datetime.datetime.now())
for kernel in ["linear"]:#,"poly","sigmoid",'rbf',]:
    clf = SVC(kernel = kernel
             ,gamma="auto"
             ,degree = 1
             ,cache_size=8000
             ).fit(xtrain, ytrain)
    result = clf.predict(xtest)
    score = clf.score(xtest,ytest)
    recall = recall_score(ytest, result)
    auc = roc_auc_score(ytest,clf.decision_function(xtest))
    print("%s 's testing accuracy %f, recall is %f', auc is %f" %(kernel,score,recall,auc))
    print(datetime.datetime.now())
    print(datetime.datetime.fromtimestamp(time()-times).strftime("%M:%S:%f"))

2020-05-25 14:59:13.570192
linear 's testing accuracy 0.841945, recall is 0.462572', auc is 0.861827
2020-05-25 15:52:31.801874
53:18:231762

In [106]:
times = time()
print(datetime.datetime.now())
for kernel in ["poly","sigmoid",'rbf',]:
    clf = SVC(kernel = kernel
             ,gamma="auto"
             ,degree = 1
             ,cache_size=8000
             ).fit(xtrain, ytrain)
    result = clf.predict(xtest)
    score = clf.score(xtest,ytest)
    recall = recall_score(ytest, result)
    auc = roc_auc_score(ytest,clf.decision_function(xtest))
    print("%s 's testing accuracy %f, recall is %f', auc is %f" %(kernel,score,recall,auc))
    print(datetime.datetime.now())
    print(datetime.datetime.fromtimestamp(time()-times).strftime("%M:%S:%f"))

2020-05-25 16:40:23.182664
poly 's testing accuracy 0.842015, recall is 0.462257', auc is 0.861843
2020-05-25 16:47:23.002579
06:59:819915
sigmoid 's testing accuracy 0.631470, recall is 0.173438', auc is 0.446864
2020-05-25 16:56:08.627930
15:45:445266
rbf 's testing accuracy 0.852096, recall is 0.496588', auc is 0.856118
2020-05-25 17:07:51.729840
27:28:547176

In [95]:
(xtrain.shape,ytrain.shape,xtest.shape,ytest.shape)

((99534, 22), (99534,), (42656, 22), (42656,))

In [92]:
pd.DataFrame(ytrain).to_csv(r'G:\机器学习资料\菜菜的skleran\08支持向量机下\ytrian.csv',encoding='gbk',index=False)
pd.DataFrame(ytest).to_csv(r'G:\机器学习资料\菜菜的skleran\08支持向量机下\ytest.csv',encoding='gbk',index=False)
xtrain.to_csv(r'G:\机器学习资料\菜菜的skleran\08支持向量机下\xtrian.csv',encoding='gbk',index=False)
xtest.to_csv(r'G:\机器学习资料\菜菜的skleran\08支持向量机下\xtest.csv',encoding='gbk',index=False)